### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by SecretGamerV071** [KaZenn-7/Steam-Keys#1]
I dont understand how to use this, could you help me?

**Comment by KaZenn-7** [comment]
Bruh did you read the README? It's literally explained there XD.

Usage
English
[Click here](https://store.steampowered.com/account/registerkey) and login with your account.

Press CTRL+SHIFT+i or F12 to enter in your browser DevTools.

Finally, just paste the code of "main.js" into Console and wait.. it will gen & check 50 keys

If Steam restrict your IP, just use VPN & private tab
